### ISSUE TITLE
Hosting your dataset on the Hugging Face Hub

### ISSUE THREAD

**Issue by lewtun** [sahil280114/codealpaca#5]
Hi @sahil280114, this is a really cool project and great job augmenting the Alpaca dataset with code instructions!

Would you be interested in hosting this on the Hugging Face Hub (https://huggingface.co/datasets)? The Alpaca dataset is also hosted there ([link](https://huggingface.co/datasets/tatsu-lab/alpaca)) and your version would be of wide interest to the community, especially since many people have noted the Alpaca models can't code very well :)

If that sounds interesting, you just need to create a new dataset repo and upload your `code_alpaca_20k.json` file through the UI. For more details, you can check out our docs [here](https://huggingface.co/docs/datasets/upload_dataset)

PS [LLaMa](https://huggingface.co/docs/transformers/main/en/model_doc/llama) is now included in the `main` branch of `transformers`, so you may also want to update your training [instructions](https://github.com/sahil280114/codealpaca#fine-tuning) :)

**Comment by sahil280114** [comment]
Hey! Love using HF datasets so makes sense to upload this, I've setup the repo and uploaded [here](https://huggingface.co/datasets/sahil2801/CodeAlpaca-20k) . Will update readme with instructions on how to use it soon.

**Comment by lewtun** [comment]
This looks awesome! Thanks for sharing it with the community 🤗
